version: 0.1.0.{build}
configuration: Release
init:
- ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME".TrimStart("v") }
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '%APPVEYOR_BUILD_VERSION%'
  assembly_file_version: '%APPVEYOR_BUILD_VERSION%'
  assembly_informational_version: '%APPVEYOR_BUILD_VERSION%'
cache:
- packages -> **\packages.config
before_build:
- ps: nuget restore .\CouchBaseProviders.sln
build_script:
- cmd: msbuild CouchBaseProviders.sln
after_build:
- ps: nuget pack CouchBaseProviders\CouchBaseProviders.nuspec -Properties "Configuration=Release;Platform=AnyCPU;" -version "$env:APPVEYOR_BUILD_VERSION"
artifacts:
- path: '*.nupkg'
test: off
deploy:
- provider: NuGet
  server: https://www.myget.org/F/couchbase-orleans-provider/api/v2/package
  api_key:
    secure: Cov0c7H0EvTAcF+4heoatFrtbFVvnz9PR0bTNbDKVTjcN47Vy1k2C3Siep6NsdA7
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: false
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: RR63qaRziTfBDzeAHNLX/nNGavXrfzgXnSRniyuFgK493SzEw8DUa89bgVZHYSg8
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
